name: Perform static code analysis through Dart CLI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, review_requested]
    branches:
      - "release/**"
      - "master/**"
  push:
    branches:
      - master
      - release

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Checkout to target branch
        run: |
          git fetch
          git checkout ${{ github.ref_name }}

      - name: Run static dart analysis with fatal infos
        run: dart analyze --fatal-infos
