name: Perform static code analysis through Dart CLI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, review_requested]
    branches:
      - "master"
  push:
    branches:
      - master
      - release

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.0"
          channel: "stable"
      - run: |
        flutter --version
        flutter pub get
        flutter analyze --fatal-infos
